default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_bucket_name: <%= ENV["s3_bucket_name"] %>
  aws_region: <%= ENV["aws_region"] %>
  aws_access_key_id: <%= ENV["aws_access_key_id"] %>
  aws_secret_access_key: <%= ENV["aws_secret_access_key"] %>


development:
  <<: *default

production:
  <<: *default

test:
  secret_key_base: 64d7151cf364993339cd62c8ae304e4b26f3d1ad3da8731cc17b5df15ef6a85141f564797e6379d47daca71fd6cded2f814a1144122de78196058991bd48bf55
